[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.demo.build]
buildCommand = "npm run build && php artisan migrate:fresh --seed --force && php artisan config:cache && php artisan cache:clear && php artisan event:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link"
